SELECT count(MATRICOLA)/TOTALE*100 PERCENTUALE, NUM_DIPART
 FROM	
		(	SELECT COUNT(MATRICOLA) AS TOTALE 
			FROM PROVA.DIPENDENTI)AS T1,
		(	SELECT * 
			FROM PROVA.DIPENDENTI) AS T2
group by NUM_DIPART

			